// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4YYqwouRY2tj3ObraCP5jeQx0iW8BUEw',
    appId: '1:965184867916:web:87028ebb50cb1e0a0f2ee9',
    messagingSenderId: '965184867916',
    projectId: 'picksy-app-5aa88',
    authDomain: 'picksy-app-5aa88.firebaseapp.com',
    storageBucket: 'picksy-app-5aa88.firebasestorage.app',
    measurementId: 'G-376Y81Q8W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjIAKnfQgLPFXOMoVum3_JwCoqE4T3m7k',
    appId: '1:965184867916:android:8c2450dc0598860e0f2ee9',
    messagingSenderId: '965184867916',
    projectId: 'picksy-app-5aa88',
    storageBucket: 'picksy-app-5aa88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4B0lPcjPzmjis3djrrEh09_Vy8Db4pc',
    appId: '1:965184867916:ios:ead35af5d0f1349a0f2ee9',
    messagingSenderId: '965184867916',
    projectId: 'picksy-app-5aa88',
    storageBucket: 'picksy-app-5aa88.firebasestorage.app',
    iosBundleId: 'com.example.picksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq4B0lPcjPzmjis3djrrEh09_Vy8Db4pc',
    appId: '1:965184867916:ios:ead35af5d0f1349a0f2ee9',
    messagingSenderId: '965184867916',
    projectId: 'picksy-app-5aa88',
    storageBucket: 'picksy-app-5aa88.firebasestorage.app',
    iosBundleId: 'com.example.picksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4YYqwouRY2tj3ObraCP5jeQx0iW8BUEw',
    appId: '1:965184867916:web:52d160433d49a70c0f2ee9',
    messagingSenderId: '965184867916',
    projectId: 'picksy-app-5aa88',
    authDomain: 'picksy-app-5aa88.firebaseapp.com',
    storageBucket: 'picksy-app-5aa88.firebasestorage.app',
    measurementId: 'G-VWHF3VYZEG',
  );
}
